/**
 * Entropy-gated crypto-adjacent secret scanning engine — Phase 5, Step 8.
 *
 * Pure file discovery + matching + fingerprinting: no Prisma/database
 * dependency, mirroring js-crypto-scan.ts exactly. secrets-detector.ts
 * layers persistence on top.
 *
 * SECURITY-SENSITIVE MODULE. This is a precision-over-recall detector, not
 * a generic "find anything password-shaped" scanner:
 *
 *   1. hardcoded string literal assignment (identifier = "..."/identifier: "...")
 *   2. length >= SECRET_MIN_LENGTH (20)
 *   3. Shannon entropy >= SECRET_MIN_ENTROPY (3.5 bits/char)
 *   4. identifier name is crypto-adjacent (see CRYPTO_ADJACENT_IDENTIFIER_RE)
 *   5. value is not on the exclusion list (env-var reference, UUID,
 *      placeholder, PEM material)
 *
 * ALL FIVE must hold. A bare `password = "hunter2"` never qualifies — either
 * the length/entropy gates reject it, or (even if long/random) the
 * identifier isn't crypto-adjacent, so it's never inspected as a candidate
 * in the first place.
 *
 * CRITICAL SAFETY INVARIANT: the raw candidate value is NEVER returned from
 * scanSourceForSecrets(), never logged, never included in any detection
 * object. Callers only ever see a SafeSecretRepresentation (a 4-character
 * preview plus a one-way SHA-256 hash) — see safeSecretRepresentation()
 * below. Grep this file for every place `value` is used if you touch it.
 */
import { readFile, stat } from "node:fs/promises";
import { createHash as sha256 } from "node:crypto";
import path from "node:path";
import fg from "fast-glob";

import { IGNORED_DIR_GLOBS, DETECTOR_MAX_FILE_BYTES, type DetectorLogger } from "./js-crypto-scan";
import type { NormalizedCryptoUsage } from "./types";

// ─── Thresholds (do not silently change) ───────────────────────────────────

export const SECRET_MIN_LENGTH = 20;
export const SECRET_MIN_ENTROPY = 3.5;

// ─── File discovery ─────────────────────────────────────────────────────────

const SECRET_SCAN_EXTENSIONS = ["js", "jsx", "ts", "tsx", "mjs", "cjs", "py", "go", "java", "rb", "php", "cs"];

/** Filenames excluded regardless of extension — lockfiles are machine-generated, never hand-authored secrets. */
const EXCLUDED_FILENAMES = new Set([
  "package-lock.json",
  "npm-shrinkwrap.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "composer.lock",
  "gemfile.lock",
  "cargo.lock",
  "poetry.lock",
  "pipfile.lock",
]);

/** Path fragments that indicate test/fixture/example data — see exclusion #12 (be conservative; this is deliberately narrow). */
const FIXTURE_PATH_SEGMENTS = ["__tests__", "__fixtures__", "__mocks__", "/test/", "/tests/", "/fixtures/", "/mocks/", "/testdata/"];

function isFixturePath(relPath: string): boolean {
  const normalized = `/${relPath.replace(/\\/g, "/").toLowerCase()}`;
  if (FIXTURE_PATH_SEGMENTS.some((seg) => normalized.includes(seg))) return true;
  const base = path.basename(normalized);
  return /\.(test|spec)\.[a-z]+$/.test(base);
}

/** Additional to IGNORED_DIR_GLOBS: directories conventionally holding generated code (e.g. this project's own src/generated/prisma). */
const GENERATED_DIR_GLOBS = ["**/generated/**", "**/__generated__/**", "**/*.generated.*"];

export async function discoverSecretScanFiles(dir: string): Promise<string[]> {
  const patterns = SECRET_SCAN_EXTENSIONS.map((ext) => `**/*.${ext}`);
  const entries = await fg(patterns, {
    cwd: dir,
    ignore: [...IGNORED_DIR_GLOBS, ...GENERATED_DIR_GLOBS],
    onlyFiles: true,
    dot: false,
    followSymbolicLinks: false,
    unique: true,
    suppressErrors: true,
  });
  return entries.filter((p) => !EXCLUDED_FILENAMES.has(path.basename(p).toLowerCase())).sort();
}

/** Content-based fallback for generated files outside a `generated/` directory: a "DO NOT EDIT"-style header in the first ~300 characters. */
const GENERATED_FILE_MARKER_RE = /generated by|do not edit|@generated|auto-generated|autogenerated/i;

export function looksGenerated(content: string): boolean {
  return GENERATED_FILE_MARKER_RE.test(content.slice(0, 300));
}

/** Reads one file, enforcing the shared per-file size cap and repo-root containment. Never throws. */
export async function readSecretScanFile(dir: string, relPath: string, onLog: DetectorLogger): Promise<string | null> {
  const resolvedRoot = path.resolve(dir);
  const absPath = path.resolve(resolvedRoot, relPath);

  if (absPath !== resolvedRoot && !absPath.startsWith(resolvedRoot + path.sep)) {
    await onLog("WARN", `[secrets] skipped file escaping repository root: ${relPath}`);
    return null;
  }

  let size: number;
  try {
    size = (await stat(absPath)).size;
  } catch {
    return null;
  }

  if (size > DETECTOR_MAX_FILE_BYTES) {
    await onLog("WARN", `[secrets] skipped ${relPath} (${size} bytes) — exceeds ${DETECTOR_MAX_FILE_BYTES}-byte limit`);
    return null;
  }

  try {
    return await readFile(absPath, "utf8");
  } catch (err) {
    await onLog("WARN", `[secrets] failed to read ${relPath}: ${err instanceof Error ? err.message : String(err)}`);
    return null;
  }
}

// ─── Shannon entropy ────────────────────────────────────────────────────────

/**
 * Shannon entropy in bits per character: H = -Σ p_i · log2(p_i), summed over
 * each distinct character's observed probability p_i in `value`. A constant
 * string ("aaaaaaaaaaaaaaaaaaaa") has H = 0; a uniformly-random string over
 * a 64-character alphabet (base64-ish) approaches H = 6. The 3.5 threshold
 * sits well below typical base64/hex secret material (~4–6 bits/char) but
 * well above natural-language text or repetitive placeholder strings
 * (~1.0–3.0 bits/char for English prose or low-variety padding).
 */
export function shannonEntropy(value: string): number {
  if (value.length === 0) return 0;
  const counts = new Map<string, number>();
  for (const ch of value) counts.set(ch, (counts.get(ch) ?? 0) + 1);

  let entropy = 0;
  for (const count of counts.values()) {
    const p = count / value.length;
    entropy -= p * Math.log2(p);
  }
  return entropy;
}

// ─── Exclusions ─────────────────────────────────────────────────────────────

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** Short placeholder words — excluded by exact match (case-insensitive) so a real secret merely *containing* "test" isn't discarded. */
const EXACT_PLACEHOLDER_VALUES = new Set(["test", "sample", "todo", "fixme", "dummy", "placeholder", "secret", "password", "example"]);

/** Longer, unambiguous placeholder phrases — excluded if the value contains them anywhere. */
const PLACEHOLDER_SUBSTRINGS = [
  "changeme",
  "change-me",
  "change_me",
  "example-secret",
  "example_secret",
  "your-secret-here",
  "your_secret_here",
  "replace-with",
  "replace_with",
  "xxxxxxxx",
];

function isPlaceholderValue(value: string): boolean {
  const lower = value.trim().toLowerCase();
  if (EXACT_PLACEHOLDER_VALUES.has(lower)) return true;
  return PLACEHOLDER_SUBSTRINGS.some((p) => lower.includes(p));
}

function isUuid(value: string): boolean {
  return UUID_RE.test(value.trim());
}

function containsPemMaterial(value: string): boolean {
  return value.includes("-----BEGIN");
}

// ─── Crypto-adjacent context ────────────────────────────────────────────────

/**
 * An identifier qualifies only when it combines a crypto/TLS term (crypto,
 * encrypt(ion), decrypt, cipher, jwt, hmac, sign(ing), tls, ssl, rsa, aes,
 * private) with a secret-shaped term (key, secret, credential, passphrase,
 * token) — matching the task's own examples (encryption key, signing key,
 * JWT signing secret, HMAC secret, private key, TLS credential). A bare
 * `password`/`token`/`secret`/`credential` identifier alone never matches:
 * that is the precision requirement this whole detector exists to enforce.
 */
const CRYPTO_ADJACENT_IDENTIFIER_RE =
  /(crypto|encrypt(ion)?|decrypt|cipher|jwt|hmac|sign(ing)?|tls|ssl|rsa|aes|private)[-_]?(key|secret|credential|passphrase|token)/i;

export function isCryptoAdjacentIdentifier(identifier: string): boolean {
  return CRYPTO_ADJACENT_IDENTIFIER_RE.test(identifier);
}

// ─── Matching (pure, no I/O) ────────────────────────────────────────────────

/**
 * Matches `identifier = "value"` / `identifier: 'value'` / `` identifier = `value` `` —
 * a simple, deliberately language-agnostic assignment/property pattern
 * (works across JS/TS/Python/Go/Java/Ruby/PHP/C# source, not a full parser
 * for any of them). The backreference (\2) ensures the opening and closing
 * quote characters match, and the value never crosses a same-type quote
 * boundary.
 */
const ASSIGNMENT_RE = /([A-Za-z_$][A-Za-z0-9_$]*)\s*[:=]\s*(["'`])((?:(?!\2).){1,500})\2/g;

export interface SecretCandidate {
  /** The variable/property name that made this crypto-adjacent — never the secret value itself. */
  identifier: string;
  relativeFilePath: string;
  lineNumber: number;
  entropy: number;
  length: number;
}

/**
 * Scans already-read source text for hardcoded crypto-adjacent secrets.
 * `resolveValue` is called with each raw candidate value so the caller can
 * fingerprint/hash it — but the raw value is discarded the instant
 * `resolveValue` returns and never appears in this function's own return
 * value.
 */
export function scanSourceForSecrets(
  content: string,
  relativeFilePath: string,
  resolveValue: (rawValue: string, lineNumber: number) => { fingerprint: string; safeName: string }
): Array<SecretCandidate & { fingerprint: string; safeName: string }> {
  const lines = content.split(/\r\n|\r|\n/);
  const results: Array<SecretCandidate & { fingerprint: string; safeName: string }> = [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const lineNumber = i + 1;

    // Exclusion: any line referencing process.env (or equivalent) is
    // skipped wholesale — conservative by design (see EXCLUSIONS #1/#2).
    // No trailing \b: "ENV[" is legitimately followed by a quote/bracket
    // (non-word chars), which would never satisfy a word-boundary check.
    if (/\b(process\.env|os\.environ|System\.getenv|ENV\[|Environment\.GetEnvironmentVariable)/.test(line)) {
      continue;
    }

    const pattern = new RegExp(ASSIGNMENT_RE.source, "g");
    let match: RegExpExecArray | null;
    while ((match = pattern.exec(line)) !== null) {
      const [full, identifier, quote, rawValue] = match;
      if (full.length === 0) {
        pattern.lastIndex++;
        continue;
      }

      // Template literal with interpolation is a dynamic value, not a
      // hardcoded one — never a genuine static secret.
      if (quote === "`" && rawValue.includes("${")) continue;

      if (!isCryptoAdjacentIdentifier(identifier)) continue;
      if (rawValue.length < SECRET_MIN_LENGTH) continue;
      if (containsPemMaterial(rawValue)) continue; // deferred to cert/key detection
      if (isUuid(rawValue)) continue;
      if (isPlaceholderValue(rawValue)) continue;

      const entropy = shannonEntropy(rawValue);
      if (entropy < SECRET_MIN_ENTROPY) continue;

      const { fingerprint, safeName } = resolveValue(rawValue, lineNumber);
      results.push({
        identifier,
        relativeFilePath,
        lineNumber,
        entropy,
        length: rawValue.length,
        fingerprint,
        safeName,
      });
    }
  }

  return results;
}

// ─── Safe representation (never the raw secret) ────────────────────────────

/**
 * Builds a safe, non-reversible representation: the first 4 characters
 * (an intentionally small preview — 4 of 20+ characters of a high-entropy
 * string leaks negligible information) plus a short slice of the SHA-256
 * hash of the *complete* value, for display uniqueness. The full SHA-256
 * hex digest (never the raw value) feeds the fingerprint separately.
 */
export function safeSecretRepresentation(rawValue: string): { safeName: string; fullHashHex: string } {
  const fullHashHex = sha256("sha256").update(rawValue, "utf8").digest("hex");
  const preview = rawValue.slice(0, 4);
  return { safeName: `SECRET_${preview}_${fullHashHex.slice(0, 12)}`, fullHashHex };
}

export function buildSecretUsage(safeName: string): NormalizedCryptoUsage {
  return {
    kind: "SECRET",
    name: safeName,
    algorithm: null,
    keyLengthBits: null,
    curve: null,
    quantumSafe: null,
    executionEnvironment: null,
  };
}

/**
 * Deterministic fingerprint from stable properties only — rule id, relative
 * path, line number, and the SHA-256 hash of the value (never the value
 * itself). Mirrors computeFingerprint()/computeCertKeyFingerprint()'s
 * "sha256-hex-of-joined-stable-parts" scheme used by every other detector.
 */
export function computeSecretFingerprint(ruleId: string, relativeFilePath: string, lineNumber: number, valueHashHex: string): string {
  const parts = [ruleId, relativeFilePath.replace(/\\/g, "/"), String(lineNumber), valueHashHex];
  return sha256("sha256").update(parts.join(" ")).digest("hex");
}

// ─── Orchestration (still pure — no persistence) ───────────────────────────

export const RULE_HARDCODED_SECRET = "secrets.hardcoded.crypto-adjacent";

export interface SecretDetection {
  ruleId: string;
  relativeFilePath: string;
  lineNumber: number;
  usage: NormalizedCryptoUsage;
  fingerprint: string;
}

/**
 * Discovers, reads and scans every eligible file. Skips fixture/test paths
 * and generated files entirely (never scanned, not merely filtered after
 * the fact) — see isFixturePath()/looksGenerated() above.
 */
export async function scanFilesForSecrets(
  dir: string,
  onLog: DetectorLogger = () => {}
): Promise<{ detections: SecretDetection[]; filesScanned: number; filesSkipped: number }> {
  const relativePaths = await discoverSecretScanFiles(dir);

  let filesScanned = 0;
  let filesSkipped = 0;
  const detections: SecretDetection[] = [];

  for (const relPath of relativePaths) {
    if (isFixturePath(relPath)) continue;

    const content = await readSecretScanFile(dir, relPath, onLog);
    if (content === null) {
      filesSkipped++;
      continue;
    }
    if (looksGenerated(content)) continue;
    filesScanned++;

    try {
      const candidates = scanSourceForSecrets(content, relPath, (rawValue, lineNumber) => {
        const { safeName, fullHashHex } = safeSecretRepresentation(rawValue);
        const fingerprint = computeSecretFingerprint(RULE_HARDCODED_SECRET, relPath, lineNumber, fullHashHex);
        return { fingerprint, safeName };
      });

      for (const candidate of candidates) {
        detections.push({
          ruleId: RULE_HARDCODED_SECRET,
          relativeFilePath: candidate.relativeFilePath,
          lineNumber: candidate.lineNumber,
          usage: buildSecretUsage(candidate.safeName),
          fingerprint: candidate.fingerprint,
        });
      }
    } catch (err) {
      // A malformed individual file must not abort the whole repository scan.
      // Never interpolate file content into this message — only the path.
      await onLog("WARN", `[secrets] failed to analyze ${relPath}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  return { detections, filesScanned, filesSkipped };
}
